export enum UploadStatus {
  AGUARDANDO = 'AGUARDANDO',
  PROCESSANDO = 'PROCESSANDO',
  PROCESSADO = 'PROCESSADO',
  ERRO = 'ERRO',
  VALIDADO = 'VALIDADO',
  EXPORTADO = 'EXPORTADO',
}

export enum StatusRevisao {
  PENDENTE = 'PENDENTE',
  EM_REVISAO = 'EM_REVISAO',
  APROVADO = 'APROVADO',
  REJEITADO = 'REJEITADO',
}

export enum TipoCartao {
  ELETRONICO = 'ELETRONICO',
  MANUSCRITO = 'MANUSCRITO',
  HIBRIDO = 'HIBRIDO',
  DESCONHECIDO = 'DESCONHECIDO',
}

export enum AcaoRevisao {
  CORRECAO = 'CORRECAO',
  APROVACAO = 'APROVACAO',
  REJEICAO = 'REJEICAO',
  OBSERVACAO = 'OBSERVACAO',
}
